### ISSUE TITLE
!! A359 VLC CSL; PLEASE; ASAP

### ISSUE THREAD

**Issue by keckromero** [oktal3700/bluebell#31]
[A359.zip](https://github.com/oktal3700/bluebell/files/6743921/A359.zip)

THE CONTAING PNG FILE IS THE PAINT OF THE VLC A359 CSL 

COULD YOU TRY TO MAKE THE 3D MODEL and MAKE THE COMPLETE CSL, I SENT YOU EVERYTHING I HAVE OF THIS FANMADE CSL MODEL

PLEASE! THE MAKER OF THIS MODEL DOES NOT ANSWER, PLEASE, ASAP!

We would realyl appreciate it :(

IT HAS NOT TO BE REALLY ACCURATE, IT ONLY HAS TO LOOK LIKE IN THE PNG

AIRLINE: AIRVALENCIA
ICAO: VLC

Best wishes and take care!

**Comment by oktal3700** [comment]
[A359_VLC.zip](https://github.com/oktal3700/bluebell/files/6747840/A359_VLC.zip)

It's no trouble. Here you go. For future reference, this is what I did:

1. Copy `A359_LIT.png` and any one of the `.obj` files.
2. Rename the `.obj` file to `A359_VLC.obj`.
3. Open `A359_VLC.obj` in a text editor and change the `TEXTURE` on line 5 to `A359_VLC.png`.
4. Create the `xsb_aircraft.txt` file.

I can't add it to the main Bluebell download because the A359 model is from a different source, but I believe you already know that.

Enjoy!

**Comment by keckromero** [comment]
Oh that was quick!

I really appreciate your work! See ya!
