### ISSUE TITLE
German Air Express VA Package

### ISSUE THREAD

**Issue by GAE074** [oktal3700/bluebell#47]
Hi Mat,
we would like to ask you for adding the GAE VA package to the BB package, thanks in advance for your help. I tried to upload the archive here in github, but got an unknown error, so please use the link, i attached.
[https://drive.google.com/file/d/15VXmfvRABgofn2OuU5NthdWqDW98nxVx/view?usp=sharing](url)
Greets Sebastian

**Comment by oktal3700** [comment]
Hi Sebastian,

I won't add the B722 because they are not repaints of models that are already in the package, but completely different models. And they are huge files, which suggests they are probably not suitable as CSL anyway (too many polygons).

I can add the others (A306, A320, A321, B733, B738, B763). I will do it when convenient.

Thank you,
Mat

**Comment by GAE074** [comment]
Hi Mat,

yes this is fine for us, the 722 (FlyJsim) is using the paints for the add on aircraft as CSL paints, too, but the rest is enough. Thanks in advance for adding the others.

Have a nice day
Sebastian
