### ISSUE TITLE
B732, B721 and B722

### ISSUE THREAD

**Issue by Claudio-2** [oktal3700/bluebell#78]
Friends, what is the possibility of having the models B732, B721 and B722 in the Bluebell directory?

**Comment by oktal3700** [comment]
The Bluebell package contains all the models that were converted from the WorldTraffic files. It is not intended to be a place for all the popular models in the flight sim world. No new models will be added, only repaints of current models. Anyone is free to create their own model package, containing whatever models they like. It could even contain models from the Bluebell package, and I hope one day someone will create that package so that I don't have to keep maintaining the Bluebell package any longer.

**Comment by Claudio-2** [comment]
Noted. Thanks.
